### ISSUE TITLE
Sorting list of all senior seminars

### ISSUE THREAD

**Issue by devshawn** [UMM-CSci/senior-seminar#11]
On the [new website](https://umm-csci.github.io/senior-seminar/seminars/), the list of all seminars should be sorted differently (in my and others opinions). Also, it should probably eventually be paginated and/or allow for sorting on other columns (jQuery datatables could be a good choice).

I propose that the list be primarily sorted _descending_ by seminar date, and then secondarily sorted _ascending_ by last name of the author. I can provide an example if necessary. 

Could you implement this @floogulinc? I think it would make it a lot easier to see recent seminars and have a more straightforward sorting of all seminars. If not, I could implement it and submit a PR, but I don't have a ton of free time. This is just a suggestion from myself and a few friends.

**Comment by floogulinc** [comment]
Reversing the sorting so it descending order of date is easy and will be implemented. Right now the second layer of sorting is based on date/time of the individual presentation, but could probably be changed to last name (would require logic to match to just the last name as name is a single field).

**Comment by emmasax1** [comment]
@devshawn:
The changes to sort initially in descending order have been made, and the page now shows pagination properly.

Regarding sorting by last name, I think that this could be helpful. However, I would argue that it's a nice-to-have. I doubt many people go through the whole list on this page; they probably instead go through by semester anyhow.

**Comment by elenam** [comment]
Fixed by #20

**Comment by floogulinc** [comment]
@elenam nothing to do with sorting was changed in #20. The sorting was changed to descending order of seminar date in 1c1061c96c5c15f291e2a1a499dcd553ef8aad1c but sorting by last name has not been added as it would be pretty difficult to implement.

**Comment by elenam** [comment]
As long as there is a search option, we don't need sorting by last name.
